import styled from 'styled-components';
import type { WikiIndexEntry } from '@/types/wiki';

const Body = styled.div`
  font-size: 15px;
  line-height: 1.75;
  color: #4a4a4a;

  p {
    margin-bottom: 18px;
  }
`;

const Stats = styled.div`
  font-size: 13px;
  color: #9b9a97;
  margin-top: 24px;
  padding-top: 16px;
  border-top: 1px solid #eee;
`;

interface WikiIndexProps {
  articles: WikiIndexEntry[];
}

export default function WikiIndex({ articles }: WikiIndexProps) {
  const directories = new Set(articles.map((a) => a.directory).filter(Boolean));

  return (
    <div>
      <Body>
        <p>
          Welcome to your personal wiki. This is a knowledge base compiled from your
          writing, conversations, bookmarks, and notes. Every article is generated by
          an LLM that reads your raw data and synthesizes it into interconnected entries.
        </p>

        <p>
          Browse by category in the sidebar, search for a topic, or hit Random to
          explore. The wiki grows as you feed it more data and run more absorb cycles.
        </p>
      </Body>

      <Stats>
        {articles.length} articles across {directories.size} categories
      </Stats>
    </div>
  );
}
